baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #39415'

defaultContentLanguageInSubdir = 'true'

# Languages

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 1
