baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41304'

[related]
  includeNewer = true
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'tags'
  weight = 100
