baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42629'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'content'
target = 'content'
lang = 'de'
