baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44549 (en)'
contentDir = 'content/en'

# Parameters
# -----------------------------------------------------------------------------

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error

# Taxonomies
# -----------------------------------------------------------------------------

[taxonomies]
genre= 'genres'
