baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #9073'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
disableKinds = []

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1
disableKinds = ['RSS']

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2
disableKinds = ['RSS', 'taxonomyTerm', 'taxonomy']

# ignoreErrors = ['error-disable-taxonomy']
[[menu.main]]
name = 'Home'
pageRef = '/'
weight = '10'

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = '20'
