baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #40357'

disableKinds = ['RSS','sitemap','taxonomy','term']

defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/english'
description = 'Kaliriu in English'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[[languages.en.menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[languages.en.menu.main]]
name = 'Projects'
pageRef = '/projects'
weight = 2

[[languages.en.menu.main]]
name = 'Blog'
pageRef = '/blog'
weight = 3

[[languages.en.menu.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4

[languages.es]
contentDir = 'content/spanish'
description = 'Kaliriu en Español'
languageCode = 'es-ES'
languageName = 'Español'
weight = 2

[[languages.es.menu.main]]
name = 'Inicio'
pageRef = '/'
weight = 1

[[languages.es.menu.main]]
name = 'Proyectos'
pageRef = '/projects'
weight = 2

[[languages.es.menu.main]]
name = 'Blog'
pageRef = '/blog'
weight = 3

[[languages.es.menu.main]]
name = 'Contacto'
pageRef = '/contact'
weight = 4
