baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #38584'

[outputFormats.content]
isHTML = true
mediaType = 'text/html'
path = 'co'

[outputs]
page = ['HTML','content']
