baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #30244'

disableKinds = ['RSS','sitemap','taxonomy','term']


[outputFormats.foo]
isPlainText = true
mediaType = 'text/plain'

[outputs]
home = ['html','foo']
