baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #36759'

[build]
writeStats = true

[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = 'node_modules/tachyons/css'
target = 'assets/css'
