baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42641'

[[cascade]]
search_ignore = true

[cascade._target]
path = "{/posts/post-1.md,/posts/post-2.md}"

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
