baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42640'
disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[[cascade]]

[cascade._build]
publishResources = false
