baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44178'

[imaging.exif]
includeFields = '.*'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Albums'
pageRef = '/albums'
weight = 20
