baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #34833'

[markup.highlight]
style = 'friendly'

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'static'
target = 'assets'
