baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #36050'

disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[mediaTypes."text/gemini"]
suffixes = ["gem"]

[outputFormats.plain]
isPlainText = true
isHTML = false
mediaType = "text/plain"
permalinkable = true
path = "txt/"

[outputFormats.gemini]
isPlainText = true
isHTML = false
mediaType = "text/gemini"
protocol = "gemini://"
permalinkable = true
path = "gemini/"
