baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #40936'

defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.fr]
contentDir = 'content/fr'
languageCode = 'fr-FR'
languageName = 'Français'
weight = 2

[languages.en.taxonomies]
category = 'categories'
tag = 'tags'

[languages.fr.taxonomies]
'catégorie' = 'catégories'
'étiquette' = 'étiquettes'
