baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41335'

disableKinds = ['RSS','sitemap','taxonomy','term']

[markup.goldmark.extensions]
typographer = false

[outputFormats.TXT]
isPlainText = true
mediaType = 'text/plain'

[outputs]
home = ['HTML','TXT']
