baseURL = "http://example.org/"
languageCode = "en-us"
title = "Hugo Forum Topic #34027"

[markup.goldmark.renderer]
  unsafe = true

[[cascade]]
  [cascade._build]
    render = "never"
    list = "never"
  [cascade._target]
    path = "/snippets/**"
