baseURL = "http://example.org/"
languageCode = "en-us"
title = "@@TITLE@@"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
[languages.en]
title = "My blog (en)"
weight = 1
contentDir = "content/en"
[languages.fr]
title = "My blog (fr)"
weight = 2
contentDir = "content/fr"
