baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43054'
paginate = 5

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
