baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41808'
disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[outputs]
home = ['HTML', 'JSON', 'JSON_2']

# We don't need to define the JSON output format. It's baked in.
[outputFormats.JSON_2]
baseName = 'index_2'
isPlainText = true
mediaType = 'application/json'
