baseURL = 'https://example.org/'
title = 'Hugo GitHub Issue #10064'

disableKinds = ['taxonomy','term']
enableRobotsTXT = true

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
disabled = true
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2
