baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42828'
disableKinds = ['RSS', 'sitemap']

[taxonomies]
'books/genre' = 'books/genres'
'films/genre' = 'films/genres'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Books'
pageRef = '/books'
weight = 20

[[menu.main]]
name = 'Films'
pageRef = '/films'
weight = 20
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2
