baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #10515'
disableKinds = ['RSS', 'taxonomy', 'term']
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
contentDir = 'content/en'
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
contentDir = 'content/de'
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = '10'

[[menu.main]]
name = 'Posts'
pageRef = 'posts'
weight = '20'
