baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43556'
disableKinds = ['RSS','sitemap','taxonomy','term','page','section']

[mediaTypes.'application/x-protobuf']
suffixes = ['pbf']
