baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42794'

[taxonomies]
tag = 'tags'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[[menu.main]]
name = 'Sitemap'
url = '/sitemap.xml'
weight = 40
