baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #36064'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
weight = 1
contentDir = 'content/en'

[languages.it]
weight = 1
contentDir = 'content/it'
