baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41755'
disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[[module.mounts]]
source = 'content'
target = 'content'

[[module.mounts]]
source = 'content/electric-cars'
target = 'content/cars'
