baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41501'

[markup.highlight]
style = 'api'

# Needed to display details element on home page, and didnt' feel like creating a short code.
[markup.goldmark.renderer]
unsafe = true
