baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #2467'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.de]
languageCode = 'de-DE'
languageName = 'Deutsch'
weight = 2

[taxonomies]
author = 'authors'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
