baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #40078'

[taxonomies]
category = 'categories'

[related]
  includeNewer = true
[[related.indices]]
  name = 'categories'
  weight = 100
