baseurl = "https://example.org/"
title = "My Site"
#theme = "loveit-original"
theme = "loveit-nekr0z"

defaultContentLanguage = "ru"

[languages.ru]
weight = 1

[languages.en]
weight = 2

[params]
version = "0.2.X"

[params.search]
enable = true

[outputs]
home = ["HTML", "JSON"]
