baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43031'
disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error
