baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44031'

defaultContentLanguage = 'sr'
defaultContentLanguageInSubdir = true

[languages.sr]
languageCode = 'sr-RS'
languageName = 'Serbian'
weight = 1

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 2

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
