baseURL = 'https://example.org/'
title = 'Hugo Forum Topic #39967'

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.fr]
languageCode = 'fr-FR'
languageName = 'Francais'
weight = 2
