baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #36724'

disableKinds = ["RSS", "section", "sitemap", "taxonomy", "term"]

[security.exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^babel$']
