baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #8279'

defaultContentLanguage = 'fragen'
defaultContentLanguageInSubdir = true

[languages.fragen]
contentDir = 'content/fragen/'
weight = 1
languageName = 'Deutsch'

[languages.pregunta] # Using 8 characters works ('preguntas' fails)
contentDir = 'content/preguntas/'
weight = 2
languageName = 'Español'

[languages.question] # Using 8 characters works ('questions' fails)
contentDir = 'content/questions/'
weight = 3
languageName = 'English'
