baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #7982'
disableKinds = ['RSS','sitemap','taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.zh]
languageCode = 'zh'
languageName = 'Chinese (zh)'
weight = 2

[languages.zh-cn]
languageCode = 'zh-cn'
languageName = 'Chinese (zh-cn)'
weight = 3
