baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #7959'

[module]
[[module.mounts]]
source = "assets"
target = "assets"
[[module.imports]]
path = "github.com/sindresorhus/modern-normalize"
[[module.imports.mounts]]
source = "modern-normalize.css"
target = "assets/scss/_modern-normalize.scss"
