baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hugo Test'
theme = 'test'
[language]
  [languages.en]
    languageCode                             = 'en-US'
    languageName                             = 'English'
    weight                                   = 1
  [languages.fr]
    languageCode                             = 'fr'
    languageName                             = 'French'
    weight                                   = 2
