baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41833'
disableKinds = ['RSS', 'sitemap', 'taxonomy', 'term']

[[cascade]]

[cascade._build]
render = 'never'

[cascade._target]
path = '**/_content.html'
