baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42762'

[taxonomies]
tag = 'tags'

[related]
includeNewer = true
threshold = 80
toLower = true

[[related.indices]]
name = 'tags'
weight = 60

[[related.indices]]
name = 'type'
weight = 30

[[cascade]]
type = 'books'

[cascade._target]
path = '/books/**'

[[cascade]]
type = 'films'

[cascade._target]
path = '/films/**'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Books'
pageRef = '/books'
weight = 20

[[menu.main]]
name = 'Films'
pageRef = '/films'
weight = 20
