baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43013'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[related.indices]]
name = 'tags'
weight = 100
