baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43346'
disableKinds = ['RSS','sitemap','taxonomy','term']

[params.render_hooks.link]
errorLevel = 'warning' # ignore (default), warning, or error

[params.render_hooks.image]
errorLevel = 'warning' # ignore (default), warning, or error

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'content/images'
target = 'assets/images'
