baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43363'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Artists'
pageRef = '/artists'
weight = 20
