baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #41443'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
languageCode = 'en-US'
languageName = 'English'
weight = 1

[languages.fr]
languageCode = 'fr-FR'
languageName = 'Francais'
weight = 2

[[languages.en.menu.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menu.main]]
name = 'Blog'
pageRef = '/'
weight = 2

[[languages.fr.menu.main]]
name = 'Home (en)'
pageRef = '/'
weight = 1
[[languages.fr.menu.main]]
name = 'Blog (fr)'
pageRef = '/'
weight = 2
