baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44116'

[permalinks]
tags = '/blog/tags/:title'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30
