baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #43063'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 20
