baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #9477'

[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = 'external'
target = 'layouts'
