baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44555'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Categories'
pageRef = '/categories'
weight = 30
