baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #37215'

disableKinds = ['sitemap','RSS','taxonomy','term']
contentDir = "content/foo"

# [[module.mounts]]
# source = "content"
# target = "content"
