baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #10926'
disableKinds = ['RSS','sitemap','taxonomy','term']

[mediaTypes.'application/x-ndjson']
suffixes = ['ndjson']

[outputFormats.ndjson]
mediaType = 'application/x-ndjson'
isPlainText = true

[outputs]
page = ['HTML','ndjson']
