baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44071'

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error
