baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo GitHub Issue #10377'

disableKinds = ['RSS','sitemap','taxonomy','term']

[permalinks]
posts = '/:sections[1]/:sections[last]/:slug'
