baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #42764'

[taxonomies]
tag = 'tags'
hobby = 'hobbies'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Hobbies'
pageRef = '/hobbies'
weight = 30

[[menu.main]]
name = 'Tags'
pageRef = '/tags'
weight = 40
