baseURL = 'https://example.org/'
languageCode = 'en-US'
title = '@@TITLE@@'
disableKinds = ['rss','section','sitemap','taxonomy','term']

[minify]
  minifyOutput = true
[minify.tdewolff.html]
  templateDelims = ["<?php","?>"]
