baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #45618'
disableKinds = ['RSS','sitemap','taxonomy','term']

[permalinks.page]
posts = '/:sections[1:]/:slug/'
[permalinks.section]
posts = '/:sections[1:]/'
