baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #45390'
disableKinds = ['RSS','sitemap','taxonomy','term']

[[module.mounts]]
source = 'content'
target = 'content'
excludeFiles = '**.tex'
