baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #11185'
disableKinds = ['RSS','sitemap','taxonomy','term']

[permalinks.page]
books = '/libros/:sections[1:]/:title'

# Works as expected
# [permalinks.section]
# books = '/libros/:sections[1:]'

# Does not work as I expect
[permalinks.section]
books = '/libros/:sections[1:last]/:title'
