baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #47192'
disableKinds = ['RSS','sitemap','taxonomy','term']

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Tutorials'
pageRef = '/tutorials'
weight = 20
