baseURL = 'https://example.org/'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# Languages
# -----------------------------------------------------------------------------

[languages.en]
baseURL = 'https://en.example.org/'
contentDir = 'content/en'
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
title = 'Hugo Forum Topic #44549 (en)'
weight = 1

[languages.de]
baseURL = 'https://de.example.org/'
contentDir = 'content/de'
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
title = 'Hugo Forum Topic #44549 (de)'
weight = 2

# Menu entries
# -----------------------------------------------------------------------------

[[menu.main]]
identifier = 'home'
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
identifier = 'books'
name = 'Books'
pageRef = '/books'
weight = 20

[[menu.main]]
identifier = 'films'
name = 'Films'
pageRef = '/films'
weight = 30

[[menu.main]]
identifier = 'genres'
name = 'Genres'
pageRef = '/genres'
weight = 40


# Parameters
# -----------------------------------------------------------------------------

[params.render_hooks.image]
errorLevel = 'error' # ignore (default), warning, or error

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error

# Taxonomies
# -----------------------------------------------------------------------------

[taxonomies]
genre= 'genres'
