baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44882'

[related]
includeNewer = true
threshold = 80
toLower = false

[[related.indices]]
name = 'tags'
weight = 100
