baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #11239'

disableKinds = ['RSS','sitemap','taxonomy','term']

[[module.mounts]]
source = 'assets'
target = 'assets'

[[module.mounts]]
source = 'images'
target = 'assets/images'
