baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #45103'

disableKinds = ['RSS','sitemap','taxonomy','term']

defaultContentLanguage = 'pl'

[outputs]
page = [ 'html']
home = [ 'html', 'imagessitemap']

[outputFormats.imagessitemap]
baseName  = 'imagessitemap'
mediaType = 'application/xml'
noUgly = true # default is false

[languages.en]
weight = 1

[languages.pl]
weight = 2

[languages.pl.outputFormats.imagessitemap]
baseName  = 'imagessitemap'
mediaType = 'application/xml'
noUgly = true # default is false
path  = 'pl'
