baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44960'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[permalinks]
posts = '/posts/:year/:slug'

[[cascade]]
layout = 'by-year'
[cascade._target]
kind = 'section'
path = '/posts/**'
