baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #45786'

[taxonomies]
level = 'level'
subject = 'subject'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Quizzes'
pageRef = '/quizzes'
weight = 20
