baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Hugo Forum Topic #44600'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

[languages.ru]
languageName = 'Russion'
weight = 1

[languages.en]
languageName = 'Deutsch'
weight = 2
