baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #10681'
disableKinds = ['RSS','sitemap','taxonomy','term']

[[module.mounts]]
source = 'data'
target = 'data'

[[module.mounts]]
source = "data-other"
target = "data/b"
