baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44744'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Products'
pageRef = '/products'
weight = 20
