baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44750'

[taxonomies]
series = "series"

[related]
includeNewer = true
threshold = 80
toLower = false
[[related.indices]]
name = 'series'
weight = 100

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menu.main]]
name = 'Writing'
pageRef = '/writing'
weight = 30

[[menu.main]]
name = 'Series'
pageRef = '/series'
weight = 40
