baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo GitHub Issue #11601'
disableKinds = ['RSS','sitemap','taxonomy','term']

# This is not necessary, but this makes it easier to see what's cached when
# testing resources.GetRemote.
[caches.getresource]
dir = ':resourceDir/_gen'
maxAge = -1
