baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '@@TITLE@@'

defaultContentLanguage = 'ru'
defaultContentLanguageInSubdir = true

[languages.ru]
languageName = 'Russion'
weight = 1

[languages.en]
languageName = 'Deutsch'
weight = 2
