baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #47192'

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Android'
pageRef = '/android'
weight = 20

[[menu.main]]
name = 'iOS'
pageRef = '/ios'
weight = 20
