baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #44976'
disableKinds = ['RSS','sitemap','taxonomy','term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages.en]
weight = 1

[languages.de]
weight = 2

[languages.de.outputFormats.json]
path = 'xx'

[outputs]
home = ['html','json']
