baseURL = 'https://example.org/'
languageCode = 'ru'
title = 'Hugo Forum Topic #44600'

disableKinds = ['RSS','taxonomy','term']

defaultContentLanguage = 'ru'

# Languages
# -----------------------------------------------------------------------------

[languages.ru]
languageName = 'Russian'
weight = 1

[languages.en]
languageName = 'English'
weight = 2

# Menu entries
# -----------------------------------------------------------------------------

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'PageX'
pageRef = '/pagex'
weight = 20

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 30

# Permalinks (intentionally empty)
# -----------------------------------------------------------------------------

[permalinks]
