baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hugo Forum Topic #46026'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menu.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20
