[[module.mounts]]
source = 'content'
target = 'content'
# replace "posts" with whatever you name your blog section; this is one of the clever bits
excludeFiles = 'posts/**/[!_]*.*md'

[[module.mounts]]
source = 'prebuild/public/content'
target = 'content'

[params.render_hooks.link]
errorLevel = 'error' # ignore (default), warning, or error (fails the build)
